export const milestones = [
  {
    followers: "4,000",
    budget: "$40",
    status: "unlocked",
    spot: "Musubi Square",
    item: "Sushi Taco Spread",
    address: "2626 W La Palma Ave, Anaheim, CA 92801",
    vibe: "Wagyu Feta Taco $9 + Soft Shell Crab $7 + Spam Trio $7 + Bulgogi Bowl ~$14",
    emoji: "🍣",
    priceNote: "~$37 for a full spread",
    mapUrl: "https://maps.google.com/?q=Musubi+Square+Anaheim",
  },
  {
    followers: "5,000",
    budget: "$50",
    status: "next",
    spot: "Tacos Los Cholos",
    item: "Prime Tacos + Cholo Pizza",
    address: "821 S State College Blvd, Anaheim, CA 92806",
    vibe: "LA Taco Madness Champs — Filet Mignon tacos $7.50ea + Cholo Pizza ~$28",
    emoji: "🌮",
    priceNote: "~$50 for prime meats + the famous pizza",
    mapUrl: "https://maps.google.com/?q=Tacos+Los+Cholos+Anaheim",
  },
  {
    followers: "6,000",
    budget: "$60",
    status: "locked",
    spot: "Anaheim Packing House",
    item: "Food Hall Crawl — 4 Vendors",
    address: "440 S Anaheim Blvd, Anaheim, CA 92805",
    vibe: "Anti-Gravity Noodles $16 + Soul Food Plate $18 + 18 Folds Dim Sum $15 + Popgelato $5",
    emoji: "🍜",
    priceNote: "~$58 across the iconic food hall",
    mapUrl: "https://maps.google.com/?q=Anaheim+Packing+House",
  },
  {
    followers: "7,000",
    budget: "$70",
    status: "locked",
    spot: "Sona Fusion Kitchen",
    item: "Vietnamese-Peruvian Fusion Feast",
    address: "2054 S Euclid St, Anaheim, CA 92802",
    vibe: "Truffle Fries $8.50 + Lomo Saltado $18 + Shrimp Wontons $11 + Pho $16.50 + Garlic Noodles $8 + Thai Tea $5",
    emoji: "🔥",
    priceNote: "~$67 for the viral late-night fusion menu",
    mapUrl: "https://maps.google.com/?q=Sona+Fusion+Kitchen+Anaheim",
  },
  {
    followers: "8,000",
    budget: "$80",
    status: "locked",
    spot: "Khan Saab",
    item: "Michelin Bib Gourmand Dinner",
    address: "1 S Lemon St, Fullerton, CA 92832",
    vibe: "Pani Puri $14 + Smoked Beef Kebab $18 + Lamb Chops $30 + Naan + Biryani",
    emoji: "👑",
    priceNote: "~$80 for a full Michelin-recognized feast",
    mapUrl: "https://maps.google.com/?q=Khan+Saab+Fullerton",
  },
  {
    followers: "9,000",
    budget: "$90",
    status: "locked",
    spot: "Heritage 71 BBQ",
    item: "Texas BBQ Meat Feast",
    address: "3451 E Miraloma Ave, Anaheim, CA 92806",
    vibe: "½lb Brisket $21 + 3 Ribs $17 + Pulled Pork $16 + Mac & Cheese + Truffle Fries $12",
    emoji: "🥩",
    priceNote: "~$88 for the full pitmaster spread",
    mapUrl: "https://maps.google.com/?q=Heritage+71+Anaheim",
  },
  {
    followers: "10,000",
    budget: "$100",
    status: "locked",
    spot: "The Wooden Pearl",
    item: "Surf & Turf Celebration",
    address: "440 S Anaheim Blvd, Anaheim, CA 92805",
    vibe: "Brand new viral spot in Packing District — premium steak, fresh seafood & craft cocktails",
    emoji: "🥂",
    priceNote: "~$100 for the ultimate 10K milestone dinner",
    mapUrl: "https://maps.google.com/?q=The+Wooden+Pearl+Anaheim",
  },
];
